export const users = [
    {
        id: "1",
        firstName: "John",
        lastName: "Doe",
        email: "john.doe@mail.com",
        location: "Calgary, AB",
        activeListings: 20,
        purchases: 20,
    },
    {
        id: "2",
        firstName: "Jane",
        lastName: "Doe",
        email: "jane.doe@mail.com",
        location: "Calgary, AB",
        activeListings: 20,
        purchases: 20,
    },
    {
        id: "3",
        firstName: "Dennis",
        lastName: "Cook",
        email: "dennis.cook@mail.com",
        location: "Calgary, AB",
        activeListings: 20,
        purchases: 20,
    },
    {
        id: "4",
        firstName: "Patricia",
        lastName: "Griffin",
        email: "patricia.griffin@mail.com",
        location: "Calgary, AB",
        activeListings: 20,
        purchases: 20,
    },
    {
        id: "5",
        firstName: "Bobby",
        lastName: "Guerrero",
        email: "bobby.guerrero@mail.com",
        location: "Calgary, AB",
        activeListings: 20,
        purchases: 20,
    },
    {
        id: "6",
        firstName: "Laurel",
        lastName: "James",
        email: "laurel.james@mail.com",
        location: "Calgary, AB",
        activeListings: 20,
        purchases: 20,
    },
    {
        id: "7",
        firstName: "Craig",
        lastName: "Matthews",
        email: "craig.matthews@mail.com",
        location: "Calgary, AB",
        activeListings: 20,
        purchases: 20,
    },
    {
        id: "8",
        firstName: "Lori",
        lastName: "Miller",
        email: "lori.miller@mail.com",
        location: "Calgary, AB",
        activeListings: 20,
        purchases: 20,
    },
    {
        id: "9",
        firstName: "Terry",
        lastName: "Gomez",
        email: "terry.gomez@mail.com",
        location: "Calgary, AB",
        activeListings: 20,
        purchases: 20,
    },
    {
        id: "10",
        firstName: "Jose",
        lastName: "Hudson",
        email: "jose.hudson@mail.com",
        location: "Calgary, AB",
        activeListings: 20,
        purchases: 20,
    }

]

export const getUserById = (id) => {
    return users.find(user => user.id === id)
}